Feat/support kaltura v7 player
openequella/openEQUELLA-Kaltura pull request #24
Opened 2024-09-04 00:15 UTC by PenghaiZhang

The Kaltura v2 player will be no longer maintained shortly, so we need to add the support for using the v7 player.

The whole support can be categories into two groups: one for New UI and the one for Old UI. We still need to support Old UI because users can watch Kaltura videos in multiple Old UI pages.

The support for New UI is mostly implemented on GitLab, but in order to include the correct player info in a search2 response, changes made in these files are also required:

- KalturaAttachmentSerializer.java
- KalturaAttachmentBean.java 

The support for Old UI is all implemented here, including:

-  Centralising relevant methods  into `KalturaService.java`, including building the embed URL, retrieving player configuration, random player ID generation etc.
-  `KalturaPreviewRenderer.java` for previewing in Legacy video gallery
-  `KalturaViewerSection.java` for watching the video in Item Summary page
-  `KalturaHandler.java` for watching and previewing a Kaltura attachment in Kaltura wizard control

In additional to above work, I also upgraded to OEQ default Kaltura player to V7 and dropped old JS files.

2024-09-04 00:39 UTC, PenghaiZhang commented on Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/service/KalturaServiceImpl.java
> +      kcf.setNameLike(DEFAULT_KALTURA_PLAYER_PREFIX);
This change means the previously created default player will be discarded, but I think this is probably OK.

2024-09-04 00:39 UTC, PenghaiZhang commented on Kaltura/com.tle.web.kaltura/src/com/tle/web/kaltura/viewer/KalturaPreviewRenderer.java
> +				TagRenderer playerScript = new AbstractComponentRenderer(new HtmlComponentState()) {
I could not find any existing `Renderer` to produce a `<script>` tag, so I just created an anonymous one here by referencing `ImageRenderer`.

2024-09-04 00:39 UTC, PenghaiZhang commented on Kaltura/com.tle.web.kaltura/src/com/tle/web/kaltura/viewer/KalturaViewerSection.java
> +  private void setupKalturaKdp(SectionInfo info, ViewItemResource resource, String width,
Big format change makes it harder to review, but the core change is in this method. 

The new approach is to populate the model and then the template file will generate UI based on the model.

2024-09-04 00:39 UTC, PenghaiZhang commented on Kaltura/com.tle.web.kaltura/src/com/tle/web/kaltura/viewer/KalturaViewerSection.java
> +  public static final class KalturaViewerSectionModel {
New model to provide details required in the template file.

2024-09-04 00:39 UTC, PenghaiZhang commented on Kaltura/com.tle.web.wizard.controls.kaltura/src/com/tle/web/controls/kaltura/KalturaAttachmentBean.java
> +  private PlayerConfig playerConfig;
The real change is this field and class `PlayerConfig`.

2024-09-04 00:39 UTC, PenghaiZhang commented on Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/service/KalturaServiceImpl.java
> +    String embedUrlPattern = playerConfig.getHtml5Url() == null ?
The Kaltura support team has confirmed that using `playerConfig.getHtml5Url() == null ` is a valid approach to determine whether a player is v2 or v7.

2024-09-09 03:44 UTC, PenghaiZhang commented on Kaltura/com.tle.web.wizard.controls.kaltura/src/com/tle/web/controls/kaltura/KalturaAttachmentBean.java
> +    this.externalId = String.format("%d/%d#%s/%s", partnerId, uiConfId, version, mediaId);
Include the version as discussed in GitLab.

2024-09-10 02:36 UTC, edalex-ian commented on Kaltura/com.tle.web.wizard.controls.kaltura/src/com/tle/web/controls/kaltura/KalturaAttachmentBean.java
> +    this.externalId = String.format("%d/%d#%s/%s", partnerId, uiConfId, version, mediaId);
As discussed in the core review for the New UI, do you think perhaps a character which doesn't require URL encoding should be used? (.e.g `-` or `_`)

2024-09-10 05:29 UTC, edalex-ian reviewed
Thanks @PenghaiZhang . There's a lot in this in the end, and very tricky to review with all the formatting stuff. But hopefully I caught most of it.

OTY.

2024-09-10 05:29 UTC, edalex-ian commented on Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/service/KalturaServiceImpl.java
> -    equellaKdpUiConf.setUseCdn(true);
Oh, I kind of see why. Down in `createPlayerEmbedUrl` you've hardcoded it into the string template.

But that then raises the question, how does that approach then relate to this? :confused:

2024-09-10 05:29 UTC, edalex-ian commented on Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/service/KalturaService.java
>  import com.kaltura.client.types.UiConf;
Just on the Kaltura library in use, have you noticed we're actually using a rather old version (17.18.1 - https://github.com/openequella/openEQUELLA-Kaltura/blob/89045ecd20676d1892b3be360647906ddf62fcb4/Kaltura/com.tle.core.kaltura/build.sbt#L4C41-L4C57)?

There's now version 20.x found with a slight change in maven coordinates: https://mvnrepository.com/artifact/com.kaltura/KalturaApiClient . And with the older coordinates - which we're currently using - there's up to version 19.x: https://mvnrepository.com/artifact/com.kaltura/kalturaApiClient

Seeing this is being done as a feature of 2024.2 should we perhaps update that?

(I guess it also highlights that we don't have renovate on this repo. :grimacing: )

2024-09-10 05:29 UTC, edalex-ian commented on Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/service/KalturaServiceImpl.java
> +        "https://cdnapisec.kaltura.com/p/{0}/sp/{1}/embedIframeJs/uiconf_id/{2}/partner_id/{0}?{3}=true&playerId={4}&entry_id={5}";
Seeing the CDN is duplicate for both of these, I suggest it should be in a constant. e.g. `final String CDN = "https://cdnapisec.kaltura.com"`.

2024-09-10 05:29 UTC, edalex-ian commented on Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/service/KalturaServiceImpl.java
> +   *
```suggestion
```

2024-09-10 05:29 UTC, edalex-ian commented on Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/service/KalturaServiceImpl.java
> +            .orElseGet(() -> getDefaultKdpUiConf(ks).getId());
I'm a bit confused by this. :thinking: 

Seeing `Integer.toString(int)` takes an `int` it will never result in an empty string. But then I'm also confused why you're converting the `int` into a `String` to then convert it back to an `int` with `Integer::parseInt`. :confused:

2024-09-10 05:29 UTC, edalex-ian commented on Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/service/KalturaServiceImpl.java
> +            .filter(id -> !Check.isEmpty(id.trim()))
No need to `trim()` here as `Check.isEmpty` does that. Further, we can remove the lambda here by using the better StringUtils. e.g.

```java
int playerId = Optional.ofNullable(confId)
  .filter(StringUtils::isNotEmpty)
  .etc
```

2024-09-10 06:19 UTC, PenghaiZhang commented on Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/service/KalturaServiceImpl.java
> +    final String TAGS = "autodeploy, kms_v5.0.0, kms_mainplayer,kalturaPlayerJs,player,ovp";
I noticed that, but this is on purpose. The text was copied from the standard player which has the inconsistent delimiters. But I guess this may not cause trouble.

2024-09-10 06:21 UTC, PenghaiZhang commented on Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/service/KalturaServiceImpl.java
> +    equellaKdpUiConf.setSwfUrl(SWF_URL);
Just try to make the default player as close to the standard player as possible. You will see the value is always a forward slash, but I guess skipping this may be OK.

2024-09-10 06:22 UTC, PenghaiZhang commented on Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/service/KalturaServiceImpl.java
> -    equellaKdpUiConf.setUseCdn(true);
I found the value was always `false` in V7 players so I removed the setting of this.

2024-09-10 06:24 UTC, PenghaiZhang commented on Kaltura/com.tle.web.wizard.controls.kaltura/src/com/tle/web/controls/kaltura/KalturaAttachmentBean.java
> +    this.externalId = String.format("%d/%d#%s/%s", partnerId, uiConfId, version, mediaId);
I will go with `-`.

2024-09-10 06:26 UTC, PenghaiZhang commented on Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/service/KalturaService.java
>  import com.kaltura.client.types.UiConf;
I did think about this, and I thought maybe I should raise a tech-debt ticket to do this separately because I did not know how much work would be required to upgrade the client API library.

2024-09-10 06:29 UTC, PenghaiZhang commented on Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/service/KalturaServiceImpl.java
> +        "https://cdnapisec.kaltura.com/p/{0}/sp/{1}/embedIframeJs/uiconf_id/{2}/partner_id/{0}?{3}=true&playerId={4}&entry_id={5}";
Good idea.

2024-09-10 06:46 UTC, PenghaiZhang commented on Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/service/KalturaServiceImpl.java
> +            .orElseGet(() -> getDefaultKdpUiConf(ks).getId());
It's confusing...probably due to the previous code about how to get the ID. 

I have tweaked how to get the conf ID so this method is no longer needed.

2024-09-11 00:31 UTC, PenghaiZhang commented on Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/service/KalturaServiceImpl.java
> +    final String CONF_VARS = "{\"versions\":{\"kaltura-ovp-player\":\"{latest}\",\"playkit-kaltura-live\":\"{latest}\",\"playkit-visibility\":\"{latest}\",\"playkit-dual-screen\":\"{latest}\",\"playk
Good idea. I have created a new json file for this.

2024-09-11 00:31 UTC, PenghaiZhang commented on Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/service/KalturaServiceImpl.java
> +    final String SWF_URL = "/";
Not a problem I will remove them.

2024-09-11 01:16 UTC, PenghaiZhang commented on Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/service/KalturaService.java
> -  boolean hasConf(KalturaServer ks, String confId);
Removed as it's no longer needed.

2024-09-11 02:01 UTC, edalex-ian requested changes
Looks good @PenghaiZhang , just a tweak to a log message and it's done.

OTY.

2024-09-11 02:01 UTC, edalex-ian commented on Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/service/KalturaServiceImpl.java
> +      LOGGER.error("Failed to get Kaltura player details for " + confId + ", use the OEQ default player instead.", e);
Should this possibly just be a warning? Also, there's a slight typo:

```suggestion
      LOGGER.warn("Failed to get Kaltura player details for " + confId + ", using the oEQ default player instead.", e);
```

2024-09-11 02:04 UTC, PenghaiZhang commented on Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/service/KalturaServiceImpl.java
> +      LOGGER.error("Failed to get Kaltura player details for " + confId + ", use the OEQ default player instead.", e);
Thanks Ian. Updated.

2024-09-11 04:29 UTC, edalex-ian approved these changes
GTG :tada:

2024-09-23 23:47 UTC, merged